### ISSUE TITLE
Request: add FREQM to samd51 boards

### ISSUE THREAD

**Issue by BitsMonger** [adafruit/Adafruit-Grand-Central-PCB#1]
I'm using both metro M4 and Grand Central boards and lot of times needed to accurately measure frequency with the Atsamd51, and I came across FREQM frequency meter feature on the chip except I can't find the right source from adafruit lib or 3rd party lib to use it. So I'm asking if adafruit could enable or add it to next package update or as a library. This assuming that FREQM can measure frequency on I/O not just for internal clock.

**Comment by ladyada** [comment]
no plans to do so, if you create code please let us know and we'll publish it!
