### ISSUE TITLE
add arduino-like diagram like Metro M4

### ISSUE THREAD

**Issue by sl1pkn07** [adafruit/Adafruit-Grand-Central-PCB#2]
Hi

Metro M4 have a arduino-like diagram https://github.com/adafruit/Adafruit-Metro-M4-Express-PCB/blob/master/Adafruit%20Metro%20M4%20Express%20Pinout.pdf

is possible create one similar for the GrandCentralM4?

greetings

**Comment by ladyada** [comment]
https://learn.adafruit.com/assets/115366
