### ISSUE TITLE
Incomplete Schematic

### ISSUE THREAD

**Issue by professorwade** [adafruit/Adafruit-Grand-Central-PCB#3]
Unless I am doing something wrong, it looks like the schematic is incomplete. Is there only one sheet, processor appears to be missing.

**Comment by caternuson** [comment]
There are two sheets. Can get images of both here:
https://learn.adafruit.com/adafruit-grand-central/downloads#schematics-3015168

In Eagle, switch between sheets using drop down:

![image](https://user-images.githubusercontent.com/8755041/212500891-4c146242-a85e-4bc7-9184-f108e33924b8.png)

**Comment by professorwade** [comment]
I apologize, my mistake. Newby error using Fusion 360.
